if (MPILIB STREQUAL impi)
  string(APPEND FFLAGS " -qmkl=cluster -xAVX2")
  string(APPEND CFLAGS " -qmkl=cluster -xAVX2")
  string(APPEND LDFLAGS " -qmkl=cluster")
  string(APPEND SLIBS " -lstdc++")
  set(MPICC "mpiicc")
  set(MPICXX "mpiicpc")
  set(MPIFC "mpiifort")
  set(SCC icc)
  set(SFC ifort)
endif()
