#!/usr/bin/env python3

"""Namelist creator for ww3
"""
import sys, os, shutil

# Typically ignore this.
# pylint: disable=invalid-name

# Disable these because this is our standard setup
# pylint: disable=wildcard-import,unused-wildcard-import,wrong-import-position
# pylint: disable=multiple-imports, too-many-locals, too-many-branches, too-many-statements
import os, shutil, sys

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "CIME", "Tools")
sys.path.append(_LIBDIR)

from standard_script_setup          import *
from CIME.buildnml                  import create_namelist_infile, parse_input
from CIME.case                      import Case
from CIME.utils                     import expect, run_cmd, safe_copy
from CIME.nmlgen                    import NamelistGenerator

logger = logging.getLogger(__name__)

####################################################################################
def _create_namelists(case, confdir, namelist_infile, nmlgen, data_list_path):
####################################################################################
    """Write out the namelist for this component."""

    config = {}
    run_type = case.get_value("RUN_TYPE")
    config["runtype"] = run_type
    config["wav_grid"] = case.get_value("WAV_GRID")

    rundir = case.get_value("RUNDIR")
    start_date = case.get_value("RUN_STARTDATE")
    start_date = start_date.replace("-","")
    start_tod = case.get_value("START_TOD")

    # determine coupling intervals
    ncpl = case.get_value('WAV_NCPL')
    if case.get_value('NCPL_BASE_PERIOD') == 'day':
        basedt = 3600 * 24
        dtime_sync = basedt // int(ncpl)
    else:
        expect(False,
               'only day base period is supported for ww3 namelist generation')

    #----------------------------------------------------
    # Write output namelist wav_in
    #----------------------------------------------------
    nmlgen.init_defaults(namelist_infile, config)

    if run_type == 'branch':
        run_refcase = case.get_value("RUN_REFCASE")
        run_refdate = case.get_value("RUN_REFDATE")
        run_tod = case.get_value("RUN_REFTOD")
        filename = "%s.ww3.r.%s-%s" %(run_refcase, run_refdate, run_tod)
        nmlgen.add_default("initfile", value=filename, ignore_abs_path=True)
    else:
        nmlgen.add_default("initfile")

    # error check 
    dtcpl = basedt / int(ncpl)
    dtmax = int(float(nmlgen.get_value('dtmax')))
    if dtcpl%dtmax != 0:
        expect(False,
               'dtcpl {} is not a multiple of dtmax {}'.format(dtcpl,dtmax))

    nmlgen.set_value("domain_percent_start", f"{start_date} {start_tod}")

    nmlgen.set_value("date_percent_field_percent_start"  , f"{start_date} {start_tod}")
    nmlgen.set_value("date_percent_restart_percent_start", f"{start_date} {start_tod}")

    nmlgen.set_value("date_percent_field_percent_stride"  , f"{dtime_sync}")
    nmlgen.set_value("date_percent_restart_percent_stride", f"{dtime_sync}")

    # write diagnostic info
    logger.debug("ww3 initial conditions file is %s", nmlgen.get_value("initfile"))

    namelist_file = os.path.join(confdir, "wav_in")
    nmlgen.write_output_file(namelist_file, data_list_path, 
                             groups=["domain_nml","input_nml","output_type_nml","output_date_nml","ww3_inparm"], 
                             sorted_groups=False)

    from pathlib import Path
    file = Path(namelist_file)
    file.write_text(file.read_text().replace('_percent_', '%'))

###############################################################################
def buildnml(case, caseroot, compname):
###############################################################################
    """Build the ww3 namelist """

    # Build the component namelist
    if compname != "ww":
        raise AttributeError

    srcroot = case.get_value("SRCROOT")
    rundir = case.get_value("RUNDIR")
    ninst = case.get_value("NINST_WAV")

    # determine the confdir directory
    confdir = os.path.join(caseroot, "Buildconf", "ww3conf")
    if not os.path.isdir(confdir):
        os.makedirs(confdir)

    #----------------------------------------------------
    # Construct the namelist generator
    #----------------------------------------------------
    # determine directory for user modified namelist_definitions.xml and namelist_defaults.xml
    user_xml_dir = os.path.join(caseroot, "SourceMods", "src.ww3")
    expect(os.path.isdir(user_xml_dir),
           "user_xml_dir %s does not exist " %user_xml_dir)

    # user definition *replaces* existing definition.
    namelist_xml_dir = os.path.join(srcroot, "components", "ww3", "cime_config")
    definition_file = [os.path.join(namelist_xml_dir, "namelist_definition_ww3.xml")]
    user_definition = os.path.join(user_xml_dir, "namelist_definition_ww3.xml")
    if os.path.isfile(user_definition):
        definition_file = [user_definition]
    for file_ in definition_file:
        expect(os.path.isfile(file_), "Namelist XML file %s not found!" % file_)

    # Create the namelist generator object - independent of instance
    nmlgen = NamelistGenerator(case, definition_file)

    #----------------------------------------------------
    # Clear out old data.
    #----------------------------------------------------
    data_list_path = os.path.join(case.get_case_root(), "Buildconf", "ww3.input_data_list")
    if os.path.exists(data_list_path):
        os.remove(data_list_path)

    #----------------------------------------------------
    # Loop over instances
    #----------------------------------------------------
    for inst_counter in range(1, ninst+1):

        # determine instance string
        inst_string = ""
        if ninst > 1:
            inst_string = '_' + '%04d' % inst_counter

        # If multi-instance case does not have restart file, use
        # single-case restart for each instance
        rpointer = "rpointer.ice"
        if (os.path.isfile(os.path.join(rundir, rpointer)) and
                (not os.path.isfile(os.path.join(rundir, rpointer + inst_string)))):
            shutil.copy(os.path.join(rundir, rpointer),
                        os.path.join(rundir, rpointer + inst_string))

        inst_string_label = inst_string
        if not inst_string_label:
            inst_string_label = "\"\""

        # create namelist_infile using user_nl_file as input
        user_nl_file = os.path.join(caseroot, "user_nl_ww3" + inst_string)
        expect(os.path.isfile(user_nl_file),
               "Missing required user_nl_file %s " %(user_nl_file))
        infile = os.path.join(confdir, "namelist_infile")
        create_namelist_infile(case, user_nl_file, infile)
        namelist_infile = [infile]

        # create namelist
        _create_namelists(case, confdir, namelist_infile, nmlgen, data_list_path)

        # copy namelist files to rundir
        if os.path.isdir(rundir):
            file1 = os.path.join(confdir, "wav_in")
            file2 = os.path.join(rundir, "wav_in")
            if inst_string:
                file2 += inst_string
            logger.debug("WW3 namelist copy: file1 %s file2 %s ", file1, file2)
            shutil.copy2(file1, file2)

    _prestage_inputs(case)
            
###############################################################################
def _prestage_inputs(case):
###############################################################################
    #----------------------------------------------------
    # Prestage necessary files to rundir
    #----------------------------------------------------
    rundir = case.get_value("RUNDIR")

    # Create rundir/ww3_moddef_create
    filename = "ww3_grid"
    bldroot = os.path.join(case.get_value("EXEROOT"),"wav","obj")
    item = os.path.join(bldroot, filename)
    if os.path.isfile(item):
        ww3_moddef_dir = os.path.join(rundir, "ww3_moddef_create")
        if not os.path.exists(ww3_moddef_dir):
            os.makedirs(ww3_moddef_dir)
        if not os.path.exists(os.path.join(ww3_moddef_dir,filename)):
            safe_copy(item, ww3_moddef_dir)

    if case.get_value("WW3_MODDEF") == 'unset':
        # Create output dir ww3_moddef_create if appropriate
        output_dir = os.path.join(rundir, "ww3_moddef_create")
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

        # Copy ww3_inp and other needed info to ww3_moddef_create directory
        input_dir = case.get_value("WW3_GRID_INP_DIR")
        files = os.listdir(input_dir)
        for filename in files:
            if not os.path.isfile(os.path.join(output_dir, filename)):
                safe_copy(os.path.join(input_dir, filename), os.path.join(output_dir, filename))
                
        # Create mod_def file using ww3_grid and the grid_input files
        if os.path.isfile(os.path.join(output_dir,"ww3_grid")):
            run_cmd("./ww3_grid > mod_def.ww3.log", from_dir=output_dir)
            if not os.path.isfile(os.path.join(output_dir,"mod_def.ww3")):
                raise RuntimeError("mod_def.ww3 was not created, check mod_def.ww3.log for errors.")
            shutil.move(os.path.join(output_dir,"mod_def.ww3"), os.path.join(rundir, "mod_def.ww3"))
        else:
            logger.warning("ww3_grid file not found. The mod_def.ww3 file will be created after the build phase.")
            
    else:
        # Use mod_def already created 
        mod_def_in = case.get_value("WW3_MODDEF")
        if os.path.isfile(mod_def_in):
            import filecmp
            copy_file = False
            if not os.path.isfile(os.path.join(rundir, "mod_def.ww3")): 
                copy_file = True
            elif not filecmp.cmp(mod_def_in, os.path.join(rundir, "mod_def.ww3")):
                copy_file = True
            if copy_file:
                shutil.copy(mod_def_in, os.path.join(rundir, "mod_def.ww3"))
        else:
            raise RuntimeError("mod_def_in {} does not exist on disk".format(mod_def_in))
            
###############################################################################
def _main_func():
###############################################################################

    # Build the component namelist

    caseroot = parse_input(sys.argv)
    with Case(caseroot) as case:
        buildnml(case, caseroot, "ww")

###############################################################################

if __name__ == "__main__":
    _main_func()
